### ISSUE TITLE
Cannot open the plot window

### ISSUE THREAD

**Issue by Kabouik** [cbarbu/R-package-zoom#10]
I just found out about this great package but unfortunately couldn't get it to work on my system:

```
> zm(rnorm(1000))
Error in if (type == "navigation") { : the condition has length > 1

> zm()
Error in recordPlot() : no current device to record from
```

When using Emacs ESS as my R REPL, I also got this:

```
> zm()
Error in getGraphicsEvent(consolePrompt = "q on the graphic window to quit") : recursive use of 'getGraphicsEvent' not supported
```

My machine runs Guix System under Wayland. I don't know if Wayland could be the issue because I also have XWayland installed (and therefore running `x11()` in R does open a new X window).

**Comment by Kabouik** [comment]
I'm stupid, sorry, I read some comment I found somewhere about `zm()` replacing `plot()` and then didn't read the manual to see that it actually is not a replacement, but has to be run after `plot()`. Sorry for the noise!

**Comment by cbarbu** [comment]
No problem, glad to find out that you figured it out.

Bests

Corentin
