### ISSUE TITLE
Navigation along a logarithmic =< 0 fails

### ISSUE THREAD

**Issue by japhir** [cbarbu/R-package-zoom#6]
Hi! I just found out about this pretty awesome R-package, thanks for the hard work! 

I have an issue when zooming/scrolling past 0 on a logarithmic axis, it throws the following errors

> Error in do.call(fn, alst) : Logarithmic axis must have positive limits
> Error in do.call(fn, alst) : CreateAtVector [log-axis()]: axp[0] = 0 < 0!
> In addition: Warning message:
> In do.call(fn, alst) : CreateAtVector "log"(from axis()): axp[0] = 0 !

code to reproduce:

``` {R}
library(zoom)
X11(type = "Xlib")
plot(1:10, 11:20, log = "x", type = "o")
zm()
```
And then obviously scroll past the x-limit.

**Comment by cbarbu** [comment]
Hey, thanks for the report. I just pushed a fix on the github repository. I had to change some core things so some testing is welcome :-)

**Comment by japhir** [comment]
Wow, that was fast! I'll need to find out how to install a package from raw code to test it, could you explain (link to) how to do it after git cloning the directory?

**Comment by cbarbu** [comment]
1) install devtools R package
install.packages("devtools")
2) go to the package folder r-package-zoom/zoom in R puis:
library("devtools")
document()
install()

c'est fait. Si tu ouvre une nouvelle session de R n'importe où sur ton
ordi, library("zoom") ouvrira la nouvelle version

On Sat, May 28, 2016 at 8:01 PM, Ilja Kocken <notifications@github.com>
wrote:

> Wow, that was fast! I'll need to find out how to install a package from
> raw code to test it, could you explain (link to) how to do it after git
> cloning the directory?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/cbarbu/R-package-zoom/issues/6#issuecomment-222321395>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAgUBA_z8bW78MqonkVvnfFplgiOpchYks5qGIMAgaJpZM4IoUI6>
> .
>



-- 
___________________
Corentin M. Barbu-Covantes
(484) 843-1580
http://scholar.google.com/citations?hl=en&user=sxDMRdQAAAAJ
"For what does it profit a man to gain the whole world, and forfeit his
soul?" Mark 8:36

**Comment by japhir** [comment]
Great! Seems to be working pretty great so far!
